---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“You are old, Father William,” the young man said,  
“And your hair has become very white;  
And yet you incessantly stand on your head –  
Do you think, at your age, it is right?”  
“In my youth,” Father William replied to his son,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
'Tis the voice of the Lobster: I heard him declare  
"You have baked me too brown, I must sugar my hair."  
As a duck with its eyelids, so he with his nose  
Trims his belt and his buttons, and turns out his toes.  
When the sands are all dry, he is gay as a lark,  
And will talk in contemptuous tones of the Shark;  
But, when the tide rises and sharks are around,  
His voice has a timid and tremulous sound.  
I passed by his garden, and marked, with one eye,  
How the Owl and the Panther were sharing a pie:  
The Panther took pie-crust, and gravy, and meat  

